services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../schema:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
  api:
    container_name: ${APP_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workdir=cmd/api
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: 8080
      DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ../:/app
    restart: always
    depends_on:
      - postgres
